language: groovy
jdk:
- openjdk7
sudo: false
branches:
  only:
  - master
before_install:
 - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
 - chmod +x ala_common.sh
 - source ./ala_common.sh
 - ala_travis_grails_setup_env
script:
 - ala_travis_grails_build
env:
  global:
  - secure: eJ76mFR1paoEoAkBd84TyYQEkWRMn5oY/Gw1cFzTKbubJVmwuFosw4PDgSOeofOuTRRUqfHdCUHLKaf1Xdv9xbh1jvINzzHOldfIGruSHkTHXI7evlglGIyIiH/ERlVjLv53hUbchBZatNbW0j/iGHG81W6u98a2mlIrbtzrNmQ=
  - secure: Z5qtw7gpIx+RIqpyaSC3ylPbBrZYVwX8vpny6dBG0RijhO5uEuk+hm8v1TAZ1XpJVebEO8HNIZydEerIiEPNWAW/RKKAsq007BtBE3rwQY9crWvLMeCrkSrXL+8rwuW8vU+DCA71tacJ2P1WLD61H877mi0pVYZQCqOULJrtIyY=
